### ISSUE TITLE
Document (ansible playbook) way to create local repo server?

### ISSUE THREAD

**Issue by ElCoyote27** [OOsemka/hextupleo#1]
Thanks for this great project,
It would be nice to have hints (or a playbook) about creating the 'Build a local repository that includes following repos '.
Can this be a simple http server on el7 exposing mirror copies of the repos or does it need something else?
Thanks,

**Comment by OOsemka** [comment]
The regular http server should work ok. Thanks for the suggestion. I'll put it on the feature list to implement.

**Comment by OOsemka** [comment]
looks like you fixed it yourself so closing this issue
